In [1]:
 # Load library
import numpy as np

In [2]:
# Generate a vector of shape (1,5) containing all zeros
vector = np.zeros(shape=5)

In [3]:
# View the vector
print(vector)

[0. 0. 0. 0. 0.]


In [4]:
# Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3,3), fill_value=1)

In [5]:
# View the vector
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
